Sync
Primogem-Craft-Development/Primogem-Craft-Fabric pull request #27
Opened 2023-11-16 13:15 UTC by Jack253-png

2023-11-16 15:21 UTC, hackermdch requested changes

2023-11-16 15:21 UTC, hackermdch commented on src/main/java/com/primogemstudio/primogemcraft/items/instances/DullBladeItem.java
> +    }
这个不是原mod里的等效写法，这样写是禁止铁砧修复，原mod是禁止砂轮修复，那是只有forge才有的

2023-11-16 15:21 UTC, hackermdch commented on src/main/java/com/primogemstudio/primogemcraft/items/instances/mora/MoraAxeItem.java
> +    }
同上

2023-11-16 15:21 UTC, hackermdch commented on src/main/java/com/primogemstudio/primogemcraft/items/instances/mora/MoraPickaxeItem.java
> +    }
同上

2023-11-16 15:21 UTC, hackermdch commented on src/main/java/com/primogemstudio/primogemcraft/items/instances/mora/MoraShovelItem.java
> +    }
同上

2023-11-16 15:21 UTC, hackermdch commented on src/main/java/com/primogemstudio/primogemcraft/items/instances/mora/MoraSwordItem.java
> +    }
同上

2023-11-17 05:39 UTC, Jack253-png commented on src/main/java/com/primogemstudio/primogemcraft/items/instances/DullBladeItem.java
> +    }
那么我应该怎么等效移植这个设定（（（

2023-11-17 07:15 UTC, hackermdch commented on src/main/java/com/primogemstudio/primogemcraft/items/instances/DullBladeItem.java
> +    }
除非写一堆mixin不然没法移植，我的建议是直接删除

2023-11-17 14:01 UTC, merged